/**
 * 学友打（がくゆうだ！）マスターデータ & モックデータ
 * GAS連携前やオフライン時にも完全に動作します。
 */
window.INITIAL_MEMBERS = [
  {
    "id": "23A2053",
    "kanji": "坂井綾太",
    "last_name": "坂井",
    "first_name": "綾太",
    "kana": "さかい りょうた",
    "kana_full": "さかいりょうた",
    "romaji": "sakai ryouta",
    "grade": 4,
    "dept": "福祉",
    "student_id": "23A2053",
    "faculty": "工学部",
    "department_name": "機械電子創成工学科",
    "birth": "2005/1/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1gHDooFLlsmmCG6zAdcu0_EnhS2HjleZe",
    "drive_id": "1gHDooFLlsmmCG6zAdcu0_EnhS2HjleZe",
    "drive_urls": [
      "1gHDooFLlsmmCG6zAdcu0_EnhS2HjleZe"
    ]
  },
  {
    "id": "23C1135",
    "kanji": "丸山直希",
    "last_name": "丸山",
    "first_name": "直希",
    "kana": "まるやま なおき",
    "kana_full": "まるやまなおき",
    "romaji": "maruyama naoki",
    "grade": 4,
    "dept": "福祉",
    "student_id": "23C1135",
    "faculty": "先進工学部",
    "department_name": "未来ロボティクス学科",
    "birth": "2004/4/12",
    "photo_url": "https://drive.google.com/uc?export=view&id=1LZnLPf9ty_BR8WQp4iw5-qfyqLR7qIYj",
    "drive_id": "1LZnLPf9ty_BR8WQp4iw5-qfyqLR7qIYj",
    "drive_urls": [
      "1LZnLPf9ty_BR8WQp4iw5-qfyqLR7qIYj"
    ]
  },
  {
    "id": "24C2025",
    "kanji": "岡崎理桜",
    "last_name": "岡崎",
    "first_name": "理桜",
    "kana": "おかざき りお",
    "kana_full": "おかざきりお",
    "romaji": "okazaki rio",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24C2025",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/4/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=1UnnSNu0dyuCThq5Dm2YsWr1GRHjBLXi0",
    "drive_id": "1UnnSNu0dyuCThq5Dm2YsWr1GRHjBLXi0",
    "drive_urls": [
      "1UnnSNu0dyuCThq5Dm2YsWr1GRHjBLXi0"
    ]
  },
  {
    "id": "24C3040",
    "kanji": "木村洸太",
    "last_name": "木村",
    "first_name": "洸太",
    "kana": "きむら こうた",
    "kana_full": "きむらこうた",
    "romaji": "kimura kouta",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24C3040",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/7/17",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "24C3060",
    "kanji": "里村茜音",
    "last_name": "里村",
    "first_name": "茜音",
    "kana": "さとむら あかね",
    "kana_full": "さとむらあかね",
    "romaji": "satomura akane",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24C3060",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/4/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1FTOXULGseZLxbY7NQpZMeoYENOb1s2UC",
    "drive_id": "1FTOXULGseZLxbY7NQpZMeoYENOb1s2UC",
    "drive_urls": [
      "1FTOXULGseZLxbY7NQpZMeoYENOb1s2UC"
    ]
  },
  {
    "id": "24C3107",
    "kanji": "福原出雲",
    "last_name": "福原",
    "first_name": "出雲",
    "kana": "ふくはら いずも",
    "kana_full": "ふくはらいずも",
    "romaji": "hukuhara izumo",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24C3107",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/12/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1bNjTIDEgIrZiYryKdFlqUAE0Q2sIjygx",
    "drive_id": "1bNjTIDEgIrZiYryKdFlqUAE0Q2sIjygx",
    "drive_urls": [
      "1bNjTIDEgIrZiYryKdFlqUAE0Q2sIjygx"
    ]
  },
  {
    "id": "24B1127",
    "kanji": "藤井美碧",
    "last_name": "藤井",
    "first_name": "美碧",
    "kana": "ふじい みのり",
    "kana_full": "ふじいみのり",
    "romaji": "huzii minori",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24B1127",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2005/10/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1hG4fpJWswx4pIigAA0Rqm2ZSlS7ke91Q",
    "drive_id": "1hG4fpJWswx4pIigAA0Rqm2ZSlS7ke91Q",
    "drive_urls": [
      "1hG4fpJWswx4pIigAA0Rqm2ZSlS7ke91Q"
    ]
  },
  {
    "id": "24C3110",
    "kanji": "古戸稜空",
    "last_name": "古戸",
    "first_name": "稜空",
    "kana": "ふると りく",
    "kana_full": "ふるとりく",
    "romaji": "huruto riku",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24C3110",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/6/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1WI0ZahGZF8YLPODU3BEwOy_qylwEtdKx",
    "drive_id": "1WI0ZahGZF8YLPODU3BEwOy_qylwEtdKx",
    "drive_urls": [
      "1WI0ZahGZF8YLPODU3BEwOy_qylwEtdKx"
    ]
  },
  {
    "id": "24G3139",
    "kanji": "吉本稜葵",
    "last_name": "吉本",
    "first_name": "稜葵",
    "kana": "よしもと いずき",
    "kana_full": "よしもといずき",
    "romaji": "yosimoto izuki",
    "grade": 3,
    "dept": "福祉",
    "student_id": "24G3139",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2006/1/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1dwe6keOQQfpJiUIPseiiWJxKQ83bFx35",
    "drive_id": "1dwe6keOQQfpJiUIPseiiWJxKQ83bFx35",
    "drive_urls": [
      "1dwe6keOQQfpJiUIPseiiWJxKQ83bFx35"
    ]
  },
  {
    "id": "25B2016",
    "kanji": "鵜沢向希",
    "last_name": "鵜沢",
    "first_name": "向希",
    "kana": "うざわ こうき",
    "kana_full": "うざわこうき",
    "romaji": "uzawa kouki",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25B2016",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2006/10/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1nBNbBAr5qUB8InwbN8IqpkF55HGMUsrd",
    "drive_id": "1nBNbBAr5qUB8InwbN8IqpkF55HGMUsrd",
    "drive_urls": [
      "1nBNbBAr5qUB8InwbN8IqpkF55HGMUsrd"
    ]
  },
  {
    "id": "25A5021",
    "kanji": "及川晃誠",
    "last_name": "及川",
    "first_name": "晃誠",
    "kana": "おいかわ こうせい",
    "kana_full": "おいかわこうせい",
    "romaji": "oikawa kousei",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25A5021",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2007/3/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1tmyKQfRBbc1hZR8onD9rh3WWs5bm2-cZ",
    "drive_id": "1tmyKQfRBbc1hZR8onD9rh3WWs5bm2-cZ",
    "drive_urls": [
      "1tmyKQfRBbc1hZR8onD9rh3WWs5bm2-cZ"
    ]
  },
  {
    "id": "25G3032",
    "kanji": "川根優希菜",
    "last_name": "川根",
    "first_name": "優希菜",
    "kana": "かわね ゆきな",
    "kana_full": "かわねゆきな",
    "romaji": "kawane yukina",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25G3032",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2006/9/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1PS1l2WlT9K90glxix_uynvWB7T9A7vra",
    "drive_id": "1PS1l2WlT9K90glxix_uynvWB7T9A7vra",
    "drive_urls": [
      "1PS1l2WlT9K90glxix_uynvWB7T9A7vra"
    ]
  },
  {
    "id": "25A6072",
    "kanji": "高山優斗",
    "last_name": "高山",
    "first_name": "優斗",
    "kana": "たかやま ゆうと",
    "kana_full": "たかやまゆうと",
    "romaji": "takayama yuuto",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25A6072",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2006/5/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=16gFJaXnba6_95xC3L9BsKl6ybZEFyanN",
    "drive_id": "16gFJaXnba6_95xC3L9BsKl6ybZEFyanN",
    "drive_urls": [
      "16gFJaXnba6_95xC3L9BsKl6ybZEFyanN"
    ]
  },
  {
    "id": "25A4126",
    "kanji": "前坂使希",
    "last_name": "前坂",
    "first_name": "使希",
    "kana": "まえさか しき",
    "kana_full": "まえさかしき",
    "romaji": "maesaka siki",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25A4126",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2006/5/4",
    "photo_url": "https://drive.google.com/uc?export=view&id=19--ULOuUXijFC3-YkgXpK0S4vTTIvkMV",
    "drive_id": "19--ULOuUXijFC3-YkgXpK0S4vTTIvkMV",
    "drive_urls": [
      "19--ULOuUXijFC3-YkgXpK0S4vTTIvkMV"
    ]
  },
  {
    "id": "25A5122",
    "kanji": "米山宏基",
    "last_name": "米山",
    "first_name": "宏基",
    "kana": "よねやま ひろき",
    "kana_full": "よねやまひろき",
    "romaji": "yoneyama hiroki",
    "grade": 2,
    "dept": "福祉",
    "student_id": "25A5122",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2006/9/8",
    "photo_url": "https://drive.google.com/uc?export=view&id=1D1HAp44lGzNzfymH22DxWPsiWigRP2VB",
    "drive_id": "1D1HAp44lGzNzfymH22DxWPsiWigRP2VB",
    "drive_urls": [
      "1D1HAp44lGzNzfymH22DxWPsiWigRP2VB"
    ]
  },
  {
    "id": "26B2046",
    "kanji": "小林暖季",
    "last_name": "小林",
    "first_name": "暖季",
    "kana": "こばやし はるき",
    "kana_full": "こばやしはるき",
    "romaji": "kobayasi haruki",
    "grade": 1,
    "dept": "福祉",
    "student_id": "26B2046",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2008/02/27",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26C1059",
    "kanji": "紺野蒼",
    "last_name": "紺野",
    "first_name": "蒼",
    "kana": "こんの あおい",
    "kana_full": "こんのあおい",
    "romaji": "konnno aoi",
    "grade": 1,
    "dept": "福祉",
    "student_id": "26C1059",
    "faculty": "先進工学部",
    "department_name": "未来ロボティクス学科",
    "birth": "2008/01/13",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A6105",
    "kanji": "真崎輝",
    "last_name": "真崎",
    "first_name": "輝",
    "kana": "まさき ひかる",
    "kana_full": "まさきひかる",
    "romaji": "masaki hikaru",
    "grade": 1,
    "dept": "福祉",
    "student_id": "26A6105",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2007/08/10",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A1169",
    "kanji": "渡邊大志",
    "last_name": "渡邊",
    "first_name": "大志",
    "kana": "わたなべ たいし",
    "kana_full": "わたなべたいし",
    "romaji": "watanabe taisi",
    "grade": 1,
    "dept": "福祉",
    "student_id": "26A1169",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2007/04/23",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "2341013",
    "kanji": "飯嶋暖乃",
    "last_name": "飯嶋",
    "first_name": "暖乃",
    "kana": "いいじま のの",
    "kana_full": "いいじまのの",
    "romaji": "iizima nono",
    "grade": 4,
    "dept": "総務",
    "student_id": "2341013",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2005/1/8",
    "photo_url": "https://drive.google.com/uc?export=view&id=1NaFX0q70PRRGpDjZQmW4IEDnrW7_IgUQ",
    "drive_id": "1NaFX0q70PRRGpDjZQmW4IEDnrW7_IgUQ",
    "drive_urls": [
      "1NaFX0q70PRRGpDjZQmW4IEDnrW7_IgUQ"
    ]
  },
  {
    "id": "23C3011",
    "kanji": "上田青奈",
    "last_name": "上田",
    "first_name": "青奈",
    "kana": "うえだ せな",
    "kana_full": "うえだせな",
    "romaji": "ueda sena",
    "grade": 4,
    "dept": "総務",
    "student_id": "23C3011",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2004/11/24",
    "photo_url": "https://drive.google.com/uc?export=view&id=1L009LJhjZeiKz3BudTL3n4YQiSX6YQW2",
    "drive_id": "1L009LJhjZeiKz3BudTL3n4YQiSX6YQW2",
    "drive_urls": [
      "1L009LJhjZeiKz3BudTL3n4YQiSX6YQW2"
    ]
  },
  {
    "id": "23A1058",
    "kanji": "栗原悠",
    "last_name": "栗原",
    "first_name": "悠",
    "kana": "くりはら ゆう",
    "kana_full": "くりはらゆう",
    "romaji": "kurihara yuu",
    "grade": 4,
    "dept": "総務",
    "student_id": "23A1058",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2004/12/28",
    "photo_url": "https://drive.google.com/uc?export=view&id=1xAeKDV4LLNZwIojuJTg9_oo0Jb_5ak6f",
    "drive_id": "1xAeKDV4LLNZwIojuJTg9_oo0Jb_5ak6f",
    "drive_urls": [
      "1xAeKDV4LLNZwIojuJTg9_oo0Jb_5ak6f"
    ]
  },
  {
    "id": "2341065",
    "kanji": "小谷津光里",
    "last_name": "小谷津",
    "first_name": "光里",
    "kana": "こやつ ひかり",
    "kana_full": "こやつひかり",
    "romaji": "koyatu hikari",
    "grade": 4,
    "dept": "総務",
    "student_id": "2341065",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2004/8/20",
    "photo_url": "https://drive.google.com/uc?export=view&id=1m_VxKCMmuaB2Eo1uQt5V5zWQas9ULiTj",
    "drive_id": "1m_VxKCMmuaB2Eo1uQt5V5zWQas9ULiTj",
    "drive_urls": [
      "1m_VxKCMmuaB2Eo1uQt5V5zWQas9ULiTj"
    ]
  },
  {
    "id": "2342078",
    "kanji": "竹本拓海",
    "last_name": "竹本",
    "first_name": "拓海",
    "kana": "たけもと たくみ",
    "kana_full": "たけもとたくみ",
    "romaji": "takemoto takumi",
    "grade": 4,
    "dept": "総務",
    "student_id": "2342078",
    "faculty": "社会システム科学部",
    "department_name": "プロジェクトマネジメント学科",
    "birth": "2004/7/13",
    "photo_url": "https://drive.google.com/uc?export=view&id=1auoDtDKEB1qj08KyZrmImRmUwdgUit8z",
    "drive_id": "1auoDtDKEB1qj08KyZrmImRmUwdgUit8z",
    "drive_urls": [
      "1auoDtDKEB1qj08KyZrmImRmUwdgUit8z"
    ]
  },
  {
    "id": "2341093",
    "kanji": "富田晃",
    "last_name": "富田",
    "first_name": "晃",
    "kana": "とみた あきら",
    "kana_full": "とみたあきら",
    "romaji": "tomita akira",
    "grade": 4,
    "dept": "総務",
    "student_id": "2341093",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2004/10/27",
    "photo_url": "https://drive.google.com/uc?export=view&id=1EGUfRvD9FPSLGwAtnmcWtUQrab6sdP5a",
    "drive_id": "1EGUfRvD9FPSLGwAtnmcWtUQrab6sdP5a",
    "drive_urls": [
      "1EGUfRvD9FPSLGwAtnmcWtUQrab6sdP5a"
    ]
  },
  {
    "id": "23A3114",
    "kanji": "根本大生",
    "last_name": "根本",
    "first_name": "大生",
    "kana": "ねもと ひろき",
    "kana_full": "ねもとひろき",
    "romaji": "nemoto hiroki",
    "grade": 4,
    "dept": "総務",
    "student_id": "23A3114",
    "faculty": "工学部",
    "department_name": "先端材料工学科",
    "birth": "2004/8/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1u_0686g_Xxn-78L9YnQU6_3B4fNcikAO",
    "drive_id": "1u_0686g_Xxn-78L9YnQU6_3B4fNcikAO",
    "drive_urls": [
      "1u_0686g_Xxn-78L9YnQU6_3B4fNcikAO"
    ]
  },
  {
    "id": "24K1030",
    "kanji": "川上丈琉",
    "last_name": "川上",
    "first_name": "丈琉",
    "kana": "かわかみ たける",
    "kana_full": "かわかみたける",
    "romaji": "kawakami takeru",
    "grade": 3,
    "dept": "総務",
    "student_id": "24K1030",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2005/7/13",
    "photo_url": "https://drive.google.com/uc?export=view&id=1ekwqP5ECKYGQ66IySoqiKrdSTl9AAXs8",
    "drive_id": "1ekwqP5ECKYGQ66IySoqiKrdSTl9AAXs8",
    "drive_urls": [
      "1ekwqP5ECKYGQ66IySoqiKrdSTl9AAXs8"
    ]
  },
  {
    "id": "24A3062",
    "kanji": "瀬上蒼太",
    "last_name": "瀬上",
    "first_name": "蒼太",
    "kana": "せのうえ そうた",
    "kana_full": "せのうえそうた",
    "romaji": "senoue souta",
    "grade": 3,
    "dept": "総務",
    "student_id": "24A3062",
    "faculty": "工学部",
    "department_name": "先端材料工学科",
    "birth": "2005/4/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Jdl4qzhyquWL6kY5yOrDm8MEfsmjgkz5",
    "drive_id": "1Jdl4qzhyquWL6kY5yOrDm8MEfsmjgkz5",
    "drive_urls": [
      "1Jdl4qzhyquWL6kY5yOrDm8MEfsmjgkz5"
    ]
  },
  {
    "id": "24A1100",
    "kanji": "田邉湧大",
    "last_name": "田邉",
    "first_name": "湧大",
    "kana": "たなべ ゆうだい",
    "kana_full": "たなべゆうだい",
    "romaji": "tanabe yuudai",
    "grade": 3,
    "dept": "総務",
    "student_id": "24A1100",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2005/6/1",
    "photo_url": "https://drive.google.com/uc?export=view&id=1nX2UB4ZqwoY4fyK-AQGrMsZTsO6if679",
    "drive_id": "1nX2UB4ZqwoY4fyK-AQGrMsZTsO6if679",
    "drive_urls": [
      "1nX2UB4ZqwoY4fyK-AQGrMsZTsO6if679"
    ]
  },
  {
    "id": "24A4106",
    "kanji": "土屋怜士",
    "last_name": "土屋",
    "first_name": "怜士",
    "kana": "つちや れいじ",
    "kana_full": "つちやれいじ",
    "romaji": "tutiya reizi",
    "grade": 3,
    "dept": "総務",
    "student_id": "24A4106",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2005/5/30",
    "photo_url": "https://drive.google.com/uc?export=view&id=1hEi_1S3S11HgzZGp_zZXhyJSMeZb6cbC",
    "drive_id": "1hEi_1S3S11HgzZGp_zZXhyJSMeZb6cbC",
    "drive_urls": [
      "1hEi_1S3S11HgzZGp_zZXhyJSMeZb6cbC"
    ]
  },
  {
    "id": "24K2108",
    "kanji": "益田康生",
    "last_name": "益田",
    "first_name": "康生",
    "kana": "ますだ こうき",
    "kana_full": "ますだこうき",
    "romaji": "masuda kouki",
    "grade": 3,
    "dept": "総務",
    "student_id": "24K2108",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2005/12/13",
    "photo_url": "https://drive.google.com/uc?export=view&id=1nHeoJCO3r1Tn-IJkwsc8RFE9j-rwJTYm",
    "drive_id": "1nHeoJCO3r1Tn-IJkwsc8RFE9j-rwJTYm",
    "drive_urls": [
      "1nHeoJCO3r1Tn-IJkwsc8RFE9j-rwJTYm"
    ]
  },
  {
    "id": "25A5008",
    "kanji": "石倉圭人",
    "last_name": "石倉",
    "first_name": "圭人",
    "kana": "いしくら けいと",
    "kana_full": "いしくらけいと",
    "romaji": "isikura keito",
    "grade": 2,
    "dept": "総務",
    "student_id": "25A5008",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2006/10/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1oRmcWCpw-BR6usg785JBNCJhMsQUS-qq",
    "drive_id": "1oRmcWCpw-BR6usg785JBNCJhMsQUS-qq",
    "drive_urls": [
      "1oRmcWCpw-BR6usg785JBNCJhMsQUS-qq"
    ]
  },
  {
    "id": "25A5059",
    "kanji": "下山田恵悠",
    "last_name": "下山田",
    "first_name": "恵悠",
    "kana": "しもやまだ よしひさ",
    "kana_full": "しもやまだよしひさ",
    "romaji": "simoyamada yosihisa",
    "grade": 2,
    "dept": "総務",
    "student_id": "25A5059",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2007/1/18",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Nqk4TyBfPT7OVZXUE7giCaQWKaU2E71B",
    "drive_id": "1Nqk4TyBfPT7OVZXUE7giCaQWKaU2E71B",
    "drive_urls": [
      "1Nqk4TyBfPT7OVZXUE7giCaQWKaU2E71B"
    ]
  },
  {
    "id": "25G3082",
    "kanji": "瀧澤朱音",
    "last_name": "瀧澤",
    "first_name": "朱音",
    "kana": "たきざわ あかね",
    "kana_full": "たきざわあかね",
    "romaji": "takizawa akane",
    "grade": 2,
    "dept": "総務",
    "student_id": "25G3082",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2006/5/9",
    "photo_url": "https://drive.google.com/uc?export=view&id=1kLlno8_e44z_nwSieHnO3-lY4jB0GFdz",
    "drive_id": "1kLlno8_e44z_nwSieHnO3-lY4jB0GFdz",
    "drive_urls": [
      "1kLlno8_e44z_nwSieHnO3-lY4jB0GFdz"
    ]
  },
  {
    "id": "25K1077",
    "kanji": "田中瑞規",
    "last_name": "田中",
    "first_name": "瑞規",
    "kana": "たなか みずき",
    "kana_full": "たなかみずき",
    "romaji": "tanaka mizuki",
    "grade": 2,
    "dept": "総務",
    "student_id": "25K1077",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2006/12/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1JnnnZk00ZZZYlSm0HSdEyT_9WTStPLoI",
    "drive_id": "1JnnnZk00ZZZYlSm0HSdEyT_9WTStPLoI",
    "drive_urls": [
      "1JnnnZk00ZZZYlSm0HSdEyT_9WTStPLoI"
    ]
  },
  {
    "id": "25C2130",
    "kanji": "山本結月",
    "last_name": "山本",
    "first_name": "結月",
    "kana": "やまもと ゆづき",
    "kana_full": "やまもとゆづき",
    "romaji": "yamamoto yuduki",
    "grade": 2,
    "dept": "総務",
    "student_id": "25C2130",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/12/26",
    "photo_url": "https://drive.google.com/uc?export=view&id=1UBq7ize_o6o39xoo5us5aEcuH0TCzagQ",
    "drive_id": "1UBq7ize_o6o39xoo5us5aEcuH0TCzagQ",
    "drive_urls": [
      "1UBq7ize_o6o39xoo5us5aEcuH0TCzagQ"
    ]
  },
  {
    "id": "25K1121",
    "kanji": "米村聖翔",
    "last_name": "米村",
    "first_name": "聖翔",
    "kana": "よねむら まさと",
    "kana_full": "よねむらまさと",
    "romaji": "yonemura masato",
    "grade": 2,
    "dept": "総務",
    "student_id": "25K1121",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2006/5/15",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Q7z1WXNd7DPHXiSqE2ZMdswznl--PS-E",
    "drive_id": "1Q7z1WXNd7DPHXiSqE2ZMdswznl--PS-E",
    "drive_urls": [
      "1Q7z1WXNd7DPHXiSqE2ZMdswznl--PS-E"
    ]
  },
  {
    "id": "25K1127",
    "kanji": "渡邊陸斗",
    "last_name": "渡邊",
    "first_name": "陸斗",
    "kana": "わたなべ りくと",
    "kana_full": "わたなべりくと",
    "romaji": "watanabe rikuto",
    "grade": 2,
    "dept": "総務",
    "student_id": "25K1127",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2006/10/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=173Q_wKBBOhE2cKjC9OxnbnouOYksdpD3",
    "drive_id": "173Q_wKBBOhE2cKjC9OxnbnouOYksdpD3",
    "drive_urls": [
      "173Q_wKBBOhE2cKjC9OxnbnouOYksdpD3"
    ]
  },
  {
    "id": "26G3001",
    "kanji": "相原悠太",
    "last_name": "相原",
    "first_name": "悠太",
    "kana": "あいはら ゆうた",
    "kana_full": "あいはらゆうた",
    "romaji": "aihara yuuta",
    "grade": 1,
    "dept": "総務",
    "student_id": "26G3001",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/10/12",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G3029",
    "kanji": "大野陽夏",
    "last_name": "大野",
    "first_name": "陽夏",
    "kana": "おおの はるか",
    "kana_full": "おおのはるか",
    "romaji": "oono haruka",
    "grade": 1,
    "dept": "総務",
    "student_id": "26G3029",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/07/11",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26K2038",
    "kanji": "小山凌矢",
    "last_name": "小山",
    "first_name": "凌矢",
    "kana": "こやま りょうや",
    "kana_full": "こやまりょうや",
    "romaji": "koyama ryouya",
    "grade": 1,
    "dept": "総務",
    "student_id": "26K2038",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2008/01/19",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "25A4075",
    "kanji": "鈴木脩太",
    "last_name": "鈴木",
    "first_name": "脩太",
    "kana": "すずき しゅうた",
    "kana_full": "すずきしゅうた",
    "romaji": "suzuki syuuta",
    "grade": 1,
    "dept": "総務",
    "student_id": "25A4075",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2006/08/15",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G1110",
    "kanji": "星野竜吾",
    "last_name": "星野",
    "first_name": "竜吾",
    "kana": "ほしの りゅうご",
    "kana_full": "ほしのりゅうご",
    "romaji": "hosino ryuugo",
    "grade": 1,
    "dept": "総務",
    "student_id": "26G1110",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2007/12/26",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "23A5018",
    "kanji": "大石啓太",
    "last_name": "大石",
    "first_name": "啓太",
    "kana": "おおいし けいた",
    "kana_full": "おおいしけいた",
    "romaji": "ooisi keita",
    "grade": 4,
    "dept": "渉外",
    "student_id": "23A5018",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2004/11/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1rVg9cKgJrWL3BmKMtQavoY6lc_8uUf5n",
    "drive_id": "1rVg9cKgJrWL3BmKMtQavoY6lc_8uUf5n",
    "drive_urls": [
      "1rVg9cKgJrWL3BmKMtQavoY6lc_8uUf5n"
    ]
  },
  {
    "id": "2342098",
    "kanji": "野崎桜咲",
    "last_name": "野崎",
    "first_name": "桜咲",
    "kana": "のざき さくら",
    "kana_full": "のざきさくら",
    "romaji": "nozaki sakura",
    "grade": 4,
    "dept": "渉外",
    "student_id": "2342098",
    "faculty": "社会システム科学部",
    "department_name": "プロジェクトマネジメント学科",
    "birth": "2004/12/13",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "24C2005",
    "kanji": "石塚真矢",
    "last_name": "石塚",
    "first_name": "真矢",
    "kana": "いしつか しんや",
    "kana_full": "いしつかしんや",
    "romaji": "isituka sinnya",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24C2005",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/12/25",
    "photo_url": "https://drive.google.com/uc?export=view&id=1RTSQW8cWP8XAz7zLSu7J4YFe-r2h7uSH",
    "drive_id": "1RTSQW8cWP8XAz7zLSu7J4YFe-r2h7uSH",
    "drive_urls": [
      "1RTSQW8cWP8XAz7zLSu7J4YFe-r2h7uSH"
    ]
  },
  {
    "id": "24B1075",
    "kanji": "佐藤志帆",
    "last_name": "佐藤",
    "first_name": "志帆",
    "kana": "さとう しほ",
    "kana_full": "さとうしほ",
    "romaji": "satou siho",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24B1075",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2005/8/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1tYwqnKtM-7dpdoq6mflMKCK6acgyTqAZ",
    "drive_id": "1tYwqnKtM-7dpdoq6mflMKCK6acgyTqAZ",
    "drive_urls": [
      "1tYwqnKtM-7dpdoq6mflMKCK6acgyTqAZ"
    ]
  },
  {
    "id": "24A5071",
    "kanji": "高橋宏典",
    "last_name": "高橋",
    "first_name": "宏典",
    "kana": "たかはし ひろのり",
    "kana_full": "たかはしひろのり",
    "romaji": "takahasi hironori",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24A5071",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2004/10/22",
    "photo_url": "https://drive.google.com/uc?export=view&id=1I9mJ_vgiLtqHiVE99nNLP9eh6Y0JsSbE",
    "drive_id": "1I9mJ_vgiLtqHiVE99nNLP9eh6Y0JsSbE",
    "drive_urls": [
      "1I9mJ_vgiLtqHiVE99nNLP9eh6Y0JsSbE"
    ]
  },
  {
    "id": "24A4122",
    "kanji": "長澤圭介",
    "last_name": "長澤",
    "first_name": "圭介",
    "kana": "ながさわ けいすけ",
    "kana_full": "ながさわけいすけ",
    "romaji": "nagasawa keisuke",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24A4122",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2005/10/31",
    "photo_url": "https://drive.google.com/uc?export=view&id=1b74W4qRNBOMfvuR48e3T7YSqIgc1pT8Z",
    "drive_id": "1b74W4qRNBOMfvuR48e3T7YSqIgc1pT8Z",
    "drive_urls": [
      "1b74W4qRNBOMfvuR48e3T7YSqIgc1pT8Z"
    ]
  },
  {
    "id": "24C2102",
    "kanji": "藤田凉",
    "last_name": "藤田",
    "first_name": "凉",
    "kana": "ふじた りょう",
    "kana_full": "ふじたりょう",
    "romaji": "huzita ryou",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24C2102",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/7/7",
    "photo_url": "https://drive.google.com/uc?export=view&id=1GhA_qupnj_1gs0dK5q1ndKl2WcyGY953",
    "drive_id": "1GhA_qupnj_1gs0dK5q1ndKl2WcyGY953",
    "drive_urls": [
      "1GhA_qupnj_1gs0dK5q1ndKl2WcyGY953"
    ]
  },
  {
    "id": "24B3120",
    "kanji": "光末真朱",
    "last_name": "光末",
    "first_name": "真朱",
    "kana": "みつすえ まそほ",
    "kana_full": "みつすえまそほ",
    "romaji": "mitusue masoho",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24B3120",
    "faculty": "創造工学部",
    "department_name": "デザイン科学科",
    "birth": "2005/11/15",
    "photo_url": "https://drive.google.com/uc?export=view&id=1FTDcocclI74RS3ntZe5L4wPhGF0mujb-",
    "drive_id": "1FTDcocclI74RS3ntZe5L4wPhGF0mujb-",
    "drive_urls": [
      "1FTDcocclI74RS3ntZe5L4wPhGF0mujb-"
    ]
  },
  {
    "id": "24C2114",
    "kanji": "宮﨑昴",
    "last_name": "宮﨑",
    "first_name": "昴",
    "kana": "みやざき すばる",
    "kana_full": "みやざきすばる",
    "romaji": "miyazaki subaru",
    "grade": 3,
    "dept": "渉外",
    "student_id": "24C2114",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/7/5",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "25A5001",
    "kanji": "相田悠希",
    "last_name": "相田",
    "first_name": "悠希",
    "kana": "あいだ はるき",
    "kana_full": "あいだはるき",
    "romaji": "aida haruki",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25A5001",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2006/10/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1hFuMULCIwadWwT7TQsBU43XsY3o4AEtG",
    "drive_id": "1hFuMULCIwadWwT7TQsBU43XsY3o4AEtG",
    "drive_urls": [
      "1hFuMULCIwadWwT7TQsBU43XsY3o4AEtG"
    ]
  },
  {
    "id": "25B1044",
    "kanji": "金沢拓翔",
    "last_name": "金沢",
    "first_name": "拓翔",
    "kana": "かなざわ たくと",
    "kana_full": "かなざわたくと",
    "romaji": "kanazawa takuto",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25B1044",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2006/4/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=1_TTUtz35l1X9a1wJwBShZGMl16AQFAGd",
    "drive_id": "1_TTUtz35l1X9a1wJwBShZGMl16AQFAGd",
    "drive_urls": [
      "1_TTUtz35l1X9a1wJwBShZGMl16AQFAGd"
    ]
  },
  {
    "id": "25A1121",
    "kanji": "藤田希花",
    "last_name": "藤田",
    "first_name": "希花",
    "kana": "ふじた ののか",
    "kana_full": "ふじたののか",
    "romaji": "huzita nonoka",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25A1121",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2006/9/22",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "25A6101",
    "kanji": "古谷駿如",
    "last_name": "古谷",
    "first_name": "駿如",
    "kana": "ふるや しゅんすけ",
    "kana_full": "ふるやしゅんすけ",
    "romaji": "huruya syunnsuke",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25A6101",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2006/9/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=1-ymojG7t9Crq-eqXgd0UdYGkvfoQWQOP",
    "drive_id": "1-ymojG7t9Crq-eqXgd0UdYGkvfoQWQOP",
    "drive_urls": [
      "1-ymojG7t9Crq-eqXgd0UdYGkvfoQWQOP"
    ]
  },
  {
    "id": "25A5125",
    "kanji": "渡邉晴琉",
    "last_name": "渡邉",
    "first_name": "晴琉",
    "kana": "わたなべ はるる",
    "kana_full": "わたなべはるる",
    "romaji": "watanabe haruru",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25A5125",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2006/8/22",
    "photo_url": "https://drive.google.com/uc?export=view&id=18mcaOc5_YlO5FGVTgAsc28u_3VoZqTrs",
    "drive_id": "18mcaOc5_YlO5FGVTgAsc28u_3VoZqTrs",
    "drive_urls": [
      "18mcaOc5_YlO5FGVTgAsc28u_3VoZqTrs"
    ]
  },
  {
    "id": "25A6125",
    "kanji": "渡辺夢叶",
    "last_name": "渡辺",
    "first_name": "夢叶",
    "kana": "わたなべ めいと",
    "kana_full": "わたなべめいと",
    "romaji": "watanabe meito",
    "grade": 2,
    "dept": "渉外",
    "student_id": "25A6125",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2006/11/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=1a41v5L7h_u7f23kJabKDiu0yO6LP86gL",
    "drive_id": "1a41v5L7h_u7f23kJabKDiu0yO6LP86gL",
    "drive_urls": [
      "1a41v5L7h_u7f23kJabKDiu0yO6LP86gL"
    ]
  },
  {
    "id": "26B2055",
    "kanji": "佐藤響稀",
    "last_name": "佐藤",
    "first_name": "響稀",
    "kana": "さとう ひびき",
    "kana_full": "さとうひびき",
    "romaji": "satou hibiki",
    "grade": 1,
    "dept": "渉外",
    "student_id": "26B2055",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2007/10/30",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G1069",
    "kanji": "鈴木博文",
    "last_name": "鈴木",
    "first_name": "博文",
    "kana": "すずき ひろふみ",
    "kana_full": "すずきひろふみ",
    "romaji": "suzuki hirohumi",
    "grade": 1,
    "dept": "渉外",
    "student_id": "26G1069",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2004/06/21",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26C3081",
    "kanji": "手塚優貴",
    "last_name": "手塚",
    "first_name": "優貴",
    "kana": "てづか ゆうき",
    "kana_full": "てづかゆうき",
    "romaji": "teduka yuuki",
    "grade": 1,
    "dept": "渉外",
    "student_id": "26C3081",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2007/05/12",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A4147",
    "kanji": "宮間智史",
    "last_name": "宮間",
    "first_name": "智史",
    "kana": "みやま さとし",
    "kana_full": "みやまさとし",
    "romaji": "miyama satosi",
    "grade": 1,
    "dept": "渉外",
    "student_id": "26A4147",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2007/09/28",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "23B2012",
    "kanji": "石川夏輝",
    "last_name": "石川",
    "first_name": "夏輝",
    "kana": "いしかわ なつき",
    "kana_full": "いしかわなつき",
    "romaji": "isikawa natuki",
    "grade": 4,
    "dept": "財務",
    "student_id": "23B2012",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2004/7/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1GFI3Du5fT7RUVZ_YOWK6G8uM6L_2_5_k",
    "drive_id": "1GFI3Du5fT7RUVZ_YOWK6G8uM6L_2_5_k",
    "drive_urls": [
      "1GFI3Du5fT7RUVZ_YOWK6G8uM6L_2_5_k"
    ]
  },
  {
    "id": "2341022",
    "kanji": "上田和正",
    "last_name": "上田",
    "first_name": "和正",
    "kana": "うえだ かずまさ",
    "kana_full": "うえだかずまさ",
    "romaji": "ueda kazumasa",
    "grade": 4,
    "dept": "財務",
    "student_id": "2341022",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2005/2/15",
    "photo_url": "https://drive.google.com/uc?export=view&id=1uTk7QfePyqESRHexIqFTp19Yk4yky66n",
    "drive_id": "1uTk7QfePyqESRHexIqFTp19Yk4yky66n",
    "drive_urls": [
      "1uTk7QfePyqESRHexIqFTp19Yk4yky66n"
    ]
  },
  {
    "id": "23B1037",
    "kanji": "川口日夏",
    "last_name": "川口",
    "first_name": "日夏",
    "kana": "かわぐち ひなつ",
    "kana_full": "かわぐちひなつ",
    "romaji": "kawaguti hinatu",
    "grade": 4,
    "dept": "財務",
    "student_id": "23B1037",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2004/7/30",
    "photo_url": "https://drive.google.com/uc?export=view&id=1lTVnf2dSgbvLZPHMpOSNZpDsUpMgyaKf",
    "drive_id": "1lTVnf2dSgbvLZPHMpOSNZpDsUpMgyaKf",
    "drive_urls": [
      "1lTVnf2dSgbvLZPHMpOSNZpDsUpMgyaKf"
    ]
  },
  {
    "id": "2341069",
    "kanji": "齋藤義正",
    "last_name": "齋藤",
    "first_name": "義正",
    "kana": "さいとう よしまさ",
    "kana_full": "さいとうよしまさ",
    "romaji": "saitou yosimasa",
    "grade": 4,
    "dept": "財務",
    "student_id": "2341069",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2004/4/30",
    "photo_url": "https://drive.google.com/uc?export=view&id=12n-hMADkbvfehFdRi2x7jHvYvW2JZIBg",
    "drive_id": "12n-hMADkbvfehFdRi2x7jHvYvW2JZIBg",
    "drive_urls": [
      "12n-hMADkbvfehFdRi2x7jHvYvW2JZIBg"
    ]
  },
  {
    "id": "23A1161",
    "kanji": "柳雄太",
    "last_name": "柳",
    "first_name": "雄太",
    "kana": "やなぎ ゆうた",
    "kana_full": "やなぎゆうた",
    "romaji": "yanagi yuuta",
    "grade": 4,
    "dept": "財務",
    "student_id": "23A1161",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2004/5/30",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Y5CfemML9Vm8OU1w9feBD0PT4EJwbdQ8",
    "drive_id": "1Y5CfemML9Vm8OU1w9feBD0PT4EJwbdQ8",
    "drive_urls": [
      "1Y5CfemML9Vm8OU1w9feBD0PT4EJwbdQ8"
    ]
  },
  {
    "id": "24G1042",
    "kanji": "鎌田素木",
    "last_name": "鎌田",
    "first_name": "素木",
    "kana": "かまた もとき",
    "kana_full": "かまたもとき",
    "romaji": "kamata motoki",
    "grade": 3,
    "dept": "財務",
    "student_id": "24G1042",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2005/9/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=16hk9tbKbny7PPtAESc6GnDpysVxJVPZ5",
    "drive_id": "16hk9tbKbny7PPtAESc6GnDpysVxJVPZ5",
    "drive_urls": [
      "16hk9tbKbny7PPtAESc6GnDpysVxJVPZ5"
    ]
  },
  {
    "id": "24K1031",
    "kanji": "川田大翔",
    "last_name": "川田",
    "first_name": "大翔",
    "kana": "かわた ひろと",
    "kana_full": "かわたひろと",
    "romaji": "kawata hiroto",
    "grade": 3,
    "dept": "財務",
    "student_id": "24K1031",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2005/7/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1B3aHgyHg0tY6YwNp7iUcm0SGHUXRIyll",
    "drive_id": "1B3aHgyHg0tY6YwNp7iUcm0SGHUXRIyll",
    "drive_urls": [
      "1B3aHgyHg0tY6YwNp7iUcm0SGHUXRIyll"
    ]
  },
  {
    "id": "24C2041",
    "kanji": "幸田麻友子",
    "last_name": "幸田",
    "first_name": "麻友子",
    "kana": "こうだ まゆこ",
    "kana_full": "こうだまゆこ",
    "romaji": "kouda mayuko",
    "grade": 3,
    "dept": "財務",
    "student_id": "24C2041",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/9/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1GFzOIH4ZHSFRE6Xur2JvDdh0QfoXS125",
    "drive_id": "1GFzOIH4ZHSFRE6Xur2JvDdh0QfoXS125",
    "drive_urls": [
      "1GFzOIH4ZHSFRE6Xur2JvDdh0QfoXS125"
    ]
  },
  {
    "id": "24G1102",
    "kanji": "冨田一之心",
    "last_name": "冨田",
    "first_name": "一之心",
    "kana": "とみた いちのしん",
    "kana_full": "とみたいちのしん",
    "romaji": "tomita itinosinn",
    "grade": 3,
    "dept": "財務",
    "student_id": "24G1102",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2006/2/28",
    "photo_url": "https://drive.google.com/uc?export=view&id=1WUqI_fPcxBeE0cRA1Fyj9xGcyZxsIRDx",
    "drive_id": "1WUqI_fPcxBeE0cRA1Fyj9xGcyZxsIRDx",
    "drive_urls": [
      "1WUqI_fPcxBeE0cRA1Fyj9xGcyZxsIRDx"
    ]
  },
  {
    "id": "25K2017",
    "kanji": "大瀬戸友",
    "last_name": "大瀬戸",
    "first_name": "戸友",
    "kana": "おおせと ゆう",
    "kana_full": "おおせとゆう",
    "romaji": "ooseto yuu",
    "grade": 2,
    "dept": "財務",
    "student_id": "25K2017",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2006/6/23",
    "photo_url": "https://drive.google.com/uc?export=view&id=1h5dT9Ns49MKQRRwkyB6X7a2r8tAjjn0p",
    "drive_id": "1h5dT9Ns49MKQRRwkyB6X7a2r8tAjjn0p",
    "drive_urls": [
      "1h5dT9Ns49MKQRRwkyB6X7a2r8tAjjn0p"
    ]
  },
  {
    "id": "24A3033",
    "kanji": "梶原晃太郎",
    "last_name": "梶原",
    "first_name": "晃太郎",
    "kana": "かじはら こうたろう",
    "kana_full": "かじはらこうたろう",
    "romaji": "kazihara koutarou",
    "grade": 2,
    "dept": "財務",
    "student_id": "24A3033",
    "faculty": "工学部",
    "department_name": "先端材料工学科",
    "birth": "2005/9/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1lus67k1az5D8vjtOnLqHqvUJrXr0Db5K",
    "drive_id": "1lus67k1az5D8vjtOnLqHqvUJrXr0Db5K",
    "drive_urls": [
      "1lus67k1az5D8vjtOnLqHqvUJrXr0Db5K"
    ]
  },
  {
    "id": "25G3029",
    "kanji": "加藤春輔",
    "last_name": "加藤",
    "first_name": "春輔",
    "kana": "かとう しゅんすけ",
    "kana_full": "かとうしゅんすけ",
    "romaji": "katou syunnsuke",
    "grade": 2,
    "dept": "財務",
    "student_id": "25G3029",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/3/23",
    "photo_url": "https://drive.google.com/uc?export=view&id=1fOOkRVwWRUuxtAf2kPQNhcViuYQQmXg_",
    "drive_id": "1fOOkRVwWRUuxtAf2kPQNhcViuYQQmXg_",
    "drive_urls": [
      "1fOOkRVwWRUuxtAf2kPQNhcViuYQQmXg_"
    ]
  },
  {
    "id": "25B2048",
    "kanji": "桑原沙季",
    "last_name": "桑原",
    "first_name": "沙季",
    "kana": "くわはら さき",
    "kana_full": "くわはらさき",
    "romaji": "kuwahara saki",
    "grade": 2,
    "dept": "財務",
    "student_id": "25B2048",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2006/11/29",
    "photo_url": "https://drive.google.com/uc?export=view&id=1vCQxGabogMCV2dGtNbd7DXfNlQwu1m2p",
    "drive_id": "1vCQxGabogMCV2dGtNbd7DXfNlQwu1m2p",
    "drive_urls": [
      "1vCQxGabogMCV2dGtNbd7DXfNlQwu1m2p"
    ]
  },
  {
    "id": "25G1064",
    "kanji": "佐土駿",
    "last_name": "佐土",
    "first_name": "駿",
    "kana": "さど しゅん",
    "kana_full": "さどしゅん",
    "romaji": "sado syunn",
    "grade": 2,
    "dept": "財務",
    "student_id": "25G1064",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2006/9/20",
    "photo_url": "https://drive.google.com/uc?export=view&id=1z9sL73Le1J-Zau7NEJQ0c6D05L_j5TCw",
    "drive_id": "1z9sL73Le1J-Zau7NEJQ0c6D05L_j5TCw",
    "drive_urls": [
      "1z9sL73Le1J-Zau7NEJQ0c6D05L_j5TCw"
    ]
  },
  {
    "id": "25A5071",
    "kanji": "田﨑太陽",
    "last_name": "田﨑",
    "first_name": "太陽",
    "kana": "たざき たいよう",
    "kana_full": "たざきたいよう",
    "romaji": "tazaki taiyou",
    "grade": 2,
    "dept": "財務",
    "student_id": "25A5071",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2005/11/30",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26C1042",
    "kanji": "川上翔",
    "last_name": "川上",
    "first_name": "翔",
    "kana": "かわかみ しょう",
    "kana_full": "かわかみしょう",
    "romaji": "kawakami syou",
    "grade": 1,
    "dept": "財務",
    "student_id": "26C1042",
    "faculty": "先進工学部",
    "department_name": "未来ロボティクス学科",
    "birth": "2006/04/06",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A1121",
    "kanji": "平澤輝一",
    "last_name": "平澤",
    "first_name": "輝一",
    "kana": "ひらさわ きいち",
    "kana_full": "ひらさわきいち",
    "romaji": "hirasawa kiiti",
    "grade": 1,
    "dept": "財務",
    "student_id": "26A1121",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2006/08/30",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26B2108",
    "kanji": "藤田夏帆",
    "last_name": "藤田",
    "first_name": "夏帆",
    "kana": "ふじた かほ",
    "kana_full": "ふじたかほ",
    "romaji": "huzita kaho",
    "grade": 1,
    "dept": "財務",
    "student_id": "26B2108",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2007/07/27",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A5126",
    "kanji": "渡辺寛大",
    "last_name": "渡辺",
    "first_name": "寛大",
    "kana": "わたなべ かんた",
    "kana_full": "わたなべかんた",
    "romaji": "watanabe kannta",
    "grade": 1,
    "dept": "財務",
    "student_id": "26A5126",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2007/11/14",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "23A6044",
    "kanji": "北村界翔",
    "last_name": "北村",
    "first_name": "界翔",
    "kana": "きたむら かいと",
    "kana_full": "きたむらかいと",
    "romaji": "kitamura kaito",
    "grade": 4,
    "dept": "広報",
    "student_id": "23A6044",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2004/6/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=1yiea6Cl9Se33c1YTifIMbqAp0I44-aIT",
    "drive_id": "1yiea6Cl9Se33c1YTifIMbqAp0I44-aIT",
    "drive_urls": [
      "1yiea6Cl9Se33c1YTifIMbqAp0I44-aIT"
    ]
  },
  {
    "id": "2342079",
    "kanji": "田嶋莉子",
    "last_name": "田嶋",
    "first_name": "莉子",
    "kana": "たじま りこ",
    "kana_full": "たじまりこ",
    "romaji": "tazima riko",
    "grade": 4,
    "dept": "広報",
    "student_id": "2342079",
    "faculty": "社会システム科学部",
    "department_name": "プロジェクトマネジメント学科",
    "birth": "2004/2/23",
    "photo_url": "https://drive.google.com/uc?export=view&id=1E_ai_PB5GuCM1jJLGiIKlURiLRNMku_H",
    "drive_id": "1E_ai_PB5GuCM1jJLGiIKlURiLRNMku_H",
    "drive_urls": [
      "1E_ai_PB5GuCM1jJLGiIKlURiLRNMku_H"
    ]
  },
  {
    "id": "2332116",
    "kanji": "中村史緒",
    "last_name": "中村",
    "first_name": "史緒",
    "kana": "なかむら しお",
    "kana_full": "なかむらしお",
    "romaji": "nakamura sio",
    "grade": 4,
    "dept": "広報",
    "student_id": "2332116",
    "faculty": "情報科学部",
    "department_name": "情報ネットワーク学科",
    "birth": "2005/1/14",
    "photo_url": "https://drive.google.com/uc?export=view&id=18lWoKj2q01xdcDVj5uBls3whwNSADTwC",
    "drive_id": "18lWoKj2q01xdcDVj5uBls3whwNSADTwC",
    "drive_urls": [
      "18lWoKj2q01xdcDVj5uBls3whwNSADTwC"
    ]
  },
  {
    "id": "23A2129",
    "kanji": "松田輝",
    "last_name": "松田",
    "first_name": "輝",
    "kana": "まつだ ひかる",
    "kana_full": "まつだひかる",
    "romaji": "matuda hikaru",
    "grade": 4,
    "dept": "広報",
    "student_id": "23A2129",
    "faculty": "工学部",
    "department_name": "機械電子創成工学科",
    "birth": "2004/9/24",
    "photo_url": "https://drive.google.com/uc?export=view&id=1bStY1L0U74Ko7ic61FUYGXJaL9x3oKh7",
    "drive_id": "1bStY1L0U74Ko7ic61FUYGXJaL9x3oKh7",
    "drive_urls": [
      "1bStY1L0U74Ko7ic61FUYGXJaL9x3oKh7"
    ]
  },
  {
    "id": "2331137",
    "kanji": "松野愛海",
    "last_name": "松野",
    "first_name": "愛海",
    "kana": "まつの あみ",
    "kana_full": "まつのあみ",
    "romaji": "matuno ami",
    "grade": 4,
    "dept": "広報",
    "student_id": "2331137",
    "faculty": "情報科学部",
    "department_name": "情報工学科",
    "birth": "2005/2/7",
    "photo_url": "https://drive.google.com/uc?export=view&id=1ec8gm__3sCAdT4-0ALCxomliOqs9Zsye",
    "drive_id": "1ec8gm__3sCAdT4-0ALCxomliOqs9Zsye",
    "drive_urls": [
      "1ec8gm__3sCAdT4-0ALCxomliOqs9Zsye"
    ]
  },
  {
    "id": "23B2125",
    "kanji": "本杉京太郎",
    "last_name": "本杉",
    "first_name": "京太郎",
    "kana": "もとすぎ きょうたろう",
    "kana_full": "もとすぎきょうたろう",
    "romaji": "motosugi kyoutarou",
    "grade": 4,
    "dept": "広報",
    "student_id": "23B2125",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2005/3/29",
    "photo_url": "https://drive.google.com/uc?export=view&id=1seE0RY2sL44zpOot7bTIPKO1xdBy-ekw",
    "drive_id": "1seE0RY2sL44zpOot7bTIPKO1xdBy-ekw",
    "drive_urls": [
      "1seE0RY2sL44zpOot7bTIPKO1xdBy-ekw"
    ]
  },
  {
    "id": "2342128",
    "kanji": "山口憧也",
    "last_name": "山口",
    "first_name": "憧也",
    "kana": "やまぐち とおや",
    "kana_full": "やまぐちとうや",
    "romaji": "yamaguti tooya",
    "grade": 4,
    "dept": "広報",
    "student_id": "2342128",
    "faculty": "社会システム科学部",
    "department_name": "プロジェクトマネジメント学科",
    "birth": "2004/8/24",
    "photo_url": "https://drive.google.com/uc?export=view&id=1MVR7sd0uIxX4ifCUTbrf5rk-z1DuUNfU",
    "drive_id": "1MVR7sd0uIxX4ifCUTbrf5rk-z1DuUNfU",
    "drive_urls": [
      "1MVR7sd0uIxX4ifCUTbrf5rk-z1DuUNfU"
    ]
  },
  {
    "id": "24A6033",
    "kanji": "小柳津涼",
    "last_name": "小柳津",
    "first_name": "涼",
    "kana": "おやいづ りょう",
    "kana_full": "おやいづりょう",
    "romaji": "oyaidu ryou",
    "grade": 3,
    "dept": "広報",
    "student_id": "24A6033",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2005/6/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1DNqaa3zZlLIoceLK8zIL7SP3i2JSjaed",
    "drive_id": "1DNqaa3zZlLIoceLK8zIL7SP3i2JSjaed",
    "drive_urls": [
      "1DNqaa3zZlLIoceLK8zIL7SP3i2JSjaed"
    ]
  },
  {
    "id": "24A6041",
    "kanji": "北見澪",
    "last_name": "北見",
    "first_name": "澪",
    "kana": "きたみ みお",
    "kana_full": "きたみみお",
    "romaji": "kitami mio",
    "grade": 3,
    "dept": "広報",
    "student_id": "24A6041",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2005/9/7",
    "photo_url": "https://drive.google.com/uc?export=view&id=1xsFCHRD1Gnk8guAJnBRHChQSDSFDHvoQ",
    "drive_id": "1xsFCHRD1Gnk8guAJnBRHChQSDSFDHvoQ",
    "drive_urls": [
      "1xsFCHRD1Gnk8guAJnBRHChQSDSFDHvoQ"
    ]
  },
  {
    "id": "24A4055",
    "kanji": "古西浩基",
    "last_name": "古西",
    "first_name": "浩基",
    "kana": "こにし こうき",
    "kana_full": "こにしこうき",
    "romaji": "konisi kouki",
    "grade": 3,
    "dept": "広報",
    "student_id": "24A4055",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2005/11/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1choWCWm1kSeZukYdO110k57mXvnEYZhJ",
    "drive_id": "1choWCWm1kSeZukYdO110k57mXvnEYZhJ",
    "drive_urls": [
      "1choWCWm1kSeZukYdO110k57mXvnEYZhJ"
    ]
  },
  {
    "id": "24C2059",
    "kanji": "佐藤由菜",
    "last_name": "佐藤",
    "first_name": "由菜",
    "kana": "さとう ゆな",
    "kana_full": "さとうゆな",
    "romaji": "satou yuna",
    "grade": 3,
    "dept": "広報",
    "student_id": "24C2059",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/3/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1iZ9vDlTGCEND4bPUFSTcOC96yhdHZY9z",
    "drive_id": "1iZ9vDlTGCEND4bPUFSTcOC96yhdHZY9z",
    "drive_urls": [
      "1iZ9vDlTGCEND4bPUFSTcOC96yhdHZY9z"
    ]
  },
  {
    "id": "24B3084",
    "kanji": "舘山向日葵",
    "last_name": "舘山",
    "first_name": "向日葵",
    "kana": "たてやま ひまわり",
    "kana_full": "たてやまひまわり",
    "romaji": "tateyama himawari",
    "grade": 3,
    "dept": "広報",
    "student_id": "24B3084",
    "faculty": "創造工学部",
    "department_name": "デザイン科学科",
    "birth": "2005/9/23",
    "photo_url": "https://drive.google.com/uc?export=view&id=15ff7_EPWgAftLNOIH9aMfVGR9qoX9Cen",
    "drive_id": "15ff7_EPWgAftLNOIH9aMfVGR9qoX9Cen",
    "drive_urls": [
      "15ff7_EPWgAftLNOIH9aMfVGR9qoX9Cen"
    ]
  },
  {
    "id": "25K2037",
    "kanji": "坂本太一",
    "last_name": "坂本",
    "first_name": "太一",
    "kana": "さかもと たいち",
    "kana_full": "さかもとたいち",
    "romaji": "sakamoto taiti",
    "grade": 2,
    "dept": "広報",
    "student_id": "25K2037",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2006/12/16",
    "photo_url": "https://drive.google.com/uc?export=view&id=1t7z5cvulr79TIXVa8O0rGlC3eiQYUH-D",
    "drive_id": "1t7z5cvulr79TIXVa8O0rGlC3eiQYUH-D",
    "drive_urls": [
      "1t7z5cvulr79TIXVa8O0rGlC3eiQYUH-D"
    ]
  },
  {
    "id": "25C2078",
    "kanji": "鈴木涼子",
    "last_name": "鈴木",
    "first_name": "涼子",
    "kana": "すずき りょうこ",
    "kana_full": "すずきりょうこ",
    "romaji": "suzuki ryouko",
    "grade": 2,
    "dept": "広報",
    "student_id": "25C2078",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/9/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=1p2Qiol8JRzVdGFs-ZH_2E8WLVIb6IbdQ",
    "drive_id": "1p2Qiol8JRzVdGFs-ZH_2E8WLVIb6IbdQ",
    "drive_urls": [
      "1p2Qiol8JRzVdGFs-ZH_2E8WLVIb6IbdQ"
    ]
  },
  {
    "id": "25G2096",
    "kanji": "西澤陽生",
    "last_name": "西澤",
    "first_name": "陽生",
    "kana": "にしざわ はるき",
    "kana_full": "にしざわはるき",
    "romaji": "nisizawa haruki",
    "grade": 2,
    "dept": "広報",
    "student_id": "25G2096",
    "faculty": "情報変革科学部",
    "department_name": "認知情報科学科",
    "birth": "2006/12/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=15sqdYn6pcgHg3TOxf0JAscq-r_8ItZq5",
    "drive_id": "15sqdYn6pcgHg3TOxf0JAscq-r_8ItZq5",
    "drive_urls": [
      "15sqdYn6pcgHg3TOxf0JAscq-r_8ItZq5"
    ]
  },
  {
    "id": "25G3123",
    "kanji": "味﨑有希",
    "last_name": "味﨑",
    "first_name": "有希",
    "kana": "みさき ゆうき",
    "kana_full": "みさきゆうき",
    "romaji": "misaki yuuki",
    "grade": 2,
    "dept": "広報",
    "student_id": "25G3123",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/3/28",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "25A4139",
    "kanji": "望月大誠",
    "last_name": "望月",
    "first_name": "大誠",
    "kana": "もちづき たいせい",
    "kana_full": "もちづきたいせい",
    "romaji": "motiduki taisei",
    "grade": 2,
    "dept": "広報",
    "student_id": "25A4139",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2006/2/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1TWbPFrvWnaWPw82-R4g7ibCsWKp3vvxa",
    "drive_id": "1TWbPFrvWnaWPw82-R4g7ibCsWKp3vvxa",
    "drive_urls": [
      "1TWbPFrvWnaWPw82-R4g7ibCsWKp3vvxa"
    ]
  },
  {
    "id": "26G1016",
    "kanji": "伊藤舞依",
    "last_name": "伊藤",
    "first_name": "舞依",
    "kana": "いとう まい",
    "kana_full": "いとうまい",
    "romaji": "itou mai",
    "grade": 1,
    "dept": "広報",
    "student_id": "26G1016",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2008/03/05",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G3062",
    "kanji": "小谷泰慶",
    "last_name": "小谷",
    "first_name": "泰慶",
    "kana": "こたに ひろよし",
    "kana_full": "こたにひろよし",
    "romaji": "kotani hiroyosi",
    "grade": 1,
    "dept": "広報",
    "student_id": "26G3062",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/10/06",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A5049",
    "kanji": "坂下朗",
    "last_name": "坂下",
    "first_name": "朗",
    "kana": "さかした あきら",
    "kana_full": "さかしたあきら",
    "romaji": "sakasita akira",
    "grade": 1,
    "dept": "広報",
    "student_id": "26A5049",
    "faculty": "工学部",
    "department_name": "情報通信システム工学科",
    "birth": "2007/08/23",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26B3064",
    "kanji": "篠塚祐輔",
    "last_name": "篠塚",
    "first_name": "祐輔",
    "kana": "しのづか ゆうすけ",
    "kana_full": "しのづかゆうすけ",
    "romaji": "sinoduka yuusuke",
    "grade": 1,
    "dept": "広報",
    "student_id": "26B3064",
    "faculty": "創造工学部",
    "department_name": "デザイン科学科",
    "birth": "2007/04/08",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "23A1001",
    "kanji": "青木遼斗",
    "last_name": "青木",
    "first_name": "遼斗",
    "kana": "あおき はると",
    "kana_full": "あおきはると",
    "romaji": "aoki haruto",
    "grade": 4,
    "dept": "厚生",
    "student_id": "23A1001",
    "faculty": "工学部",
    "department_name": "機械工学科",
    "birth": "2004/6/17",
    "photo_url": "https://drive.google.com/uc?export=view&id=1DPgkt7BJcpdWwtScxg3t7yDkWywh5-JC",
    "drive_id": "1DPgkt7BJcpdWwtScxg3t7yDkWywh5-JC",
    "drive_urls": [
      "1DPgkt7BJcpdWwtScxg3t7yDkWywh5-JC"
    ]
  },
  {
    "id": "23A2029",
    "kanji": "金澤明輝",
    "last_name": "金澤",
    "first_name": "明輝",
    "kana": "かなざわ はるき",
    "kana_full": "かなざわはるき",
    "romaji": "kanazawa haruki",
    "grade": 4,
    "dept": "厚生",
    "student_id": "23A2029",
    "faculty": "工学部",
    "department_name": "機械電子創成工学科",
    "birth": "2004/8/21",
    "photo_url": "https://drive.google.com/uc?export=view&id=1kFtbY4PrBrHjmc1RJsdP2vrgAVJmqhFs",
    "drive_id": "1kFtbY4PrBrHjmc1RJsdP2vrgAVJmqhFs",
    "drive_urls": [
      "1kFtbY4PrBrHjmc1RJsdP2vrgAVJmqhFs"
    ]
  },
  {
    "id": "23A4114",
    "kanji": "田辺和也",
    "last_name": "田辺",
    "first_name": "和也",
    "kana": "たなべ かずや",
    "kana_full": "たなべかずや",
    "romaji": "tanabe kazuya",
    "grade": 4,
    "dept": "厚生",
    "student_id": "23A4114",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2004/10/22",
    "photo_url": "https://drive.google.com/uc?export=view&id=1mu4EIpJA8VnjisIw_1As0p17TwyHShqQ",
    "drive_id": "1mu4EIpJA8VnjisIw_1As0p17TwyHShqQ",
    "drive_urls": [
      "1mu4EIpJA8VnjisIw_1As0p17TwyHShqQ"
    ]
  },
  {
    "id": "24C2037",
    "kanji": "工藤圭悟",
    "last_name": "工藤",
    "first_name": "圭悟",
    "kana": "くどう けいご",
    "kana_full": "くどうけいご",
    "romaji": "kudou keigo",
    "grade": 3,
    "dept": "厚生",
    "student_id": "24C2037",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/9/1",
    "photo_url": "https://drive.google.com/uc?export=view&id=1m-XBRHoVMAikLcl0gCU0Uf7l2S-Dee0Y",
    "drive_id": "1m-XBRHoVMAikLcl0gCU0Uf7l2S-Dee0Y",
    "drive_urls": [
      "1m-XBRHoVMAikLcl0gCU0Uf7l2S-Dee0Y"
    ]
  },
  {
    "id": "24A6043",
    "kanji": "熊谷來実",
    "last_name": "熊谷",
    "first_name": "來実",
    "kana": "くまがい くるみ",
    "kana_full": "くまがいくるみ",
    "romaji": "kumagai kurumi",
    "grade": 3,
    "dept": "厚生",
    "student_id": "24A6043",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2005/8/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1EfSRG4doOn8nvr2fooJJvYKpsiyCWkxS",
    "drive_id": "1EfSRG4doOn8nvr2fooJJvYKpsiyCWkxS",
    "drive_urls": [
      "1EfSRG4doOn8nvr2fooJJvYKpsiyCWkxS"
    ]
  },
  {
    "id": "24C2047",
    "kanji": "齋藤蒼天",
    "last_name": "齋藤",
    "first_name": "蒼天",
    "kana": "さいとう そら",
    "kana_full": "さいとうそら",
    "romaji": "saitou sora",
    "grade": 3,
    "dept": "厚生",
    "student_id": "24C2047",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/3/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=1PnNWziyTPYRIFDoTDW0EV-I7zwIwwyK4",
    "drive_id": "1PnNWziyTPYRIFDoTDW0EV-I7zwIwwyK4",
    "drive_urls": [
      "1PnNWziyTPYRIFDoTDW0EV-I7zwIwwyK4"
    ]
  },
  {
    "id": "24C2070",
    "kanji": "高島春香",
    "last_name": "高島",
    "first_name": "春香",
    "kana": "たかしま はるか",
    "kana_full": "たかしまはるか",
    "romaji": "takasima haruka",
    "grade": 3,
    "dept": "厚生",
    "student_id": "24C2070",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/1/25",
    "photo_url": "https://drive.google.com/uc?export=view&id=1eaADKb7UOBGTyPhoaqWw7NmdnklDRuQx",
    "drive_id": "1eaADKb7UOBGTyPhoaqWw7NmdnklDRuQx",
    "drive_urls": [
      "1eaADKb7UOBGTyPhoaqWw7NmdnklDRuQx"
    ]
  },
  {
    "id": "24C3105",
    "kanji": "廣瀬雅人",
    "last_name": "廣瀬",
    "first_name": "雅人",
    "kana": "ひろせ まさと",
    "kana_full": "ひろせまさと",
    "romaji": "hirose masato",
    "grade": 3,
    "dept": "厚生",
    "student_id": "24C3105",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/5/2",
    "photo_url": "https://drive.google.com/uc?export=view&id=18PDfnoysC8gZgN7BfbK2qNxK4BYj3mic",
    "drive_id": "18PDfnoysC8gZgN7BfbK2qNxK4BYj3mic",
    "drive_urls": [
      "18PDfnoysC8gZgN7BfbK2qNxK4BYj3mic"
    ]
  },
  {
    "id": "25G2043",
    "kanji": "金成永樹",
    "last_name": "金成",
    "first_name": "永樹",
    "kana": "かなり えいき",
    "kana_full": "かなりえいき",
    "romaji": "kanari eiki",
    "grade": 2,
    "dept": "厚生",
    "student_id": "25G2043",
    "faculty": "情報変革科学部",
    "department_name": "認知情報科学科",
    "birth": "2006/7/16",
    "photo_url": "https://drive.google.com/uc?export=view&id=13g1CYadWidNEKEFsc_szKuddR-auO6mQ",
    "drive_id": "13g1CYadWidNEKEFsc_szKuddR-auO6mQ",
    "drive_urls": [
      "13g1CYadWidNEKEFsc_szKuddR-auO6mQ"
    ]
  },
  {
    "id": "24C3044",
    "kanji": "近藤優大",
    "last_name": "近藤",
    "first_name": "優大",
    "kana": "こんどう ゆうた",
    "kana_full": "こんどうゆうた",
    "romaji": "konndou yuuta",
    "grade": 2,
    "dept": "厚生",
    "student_id": "24C3044",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2004/4/30",
    "photo_url": "https://drive.google.com/uc?export=view&id=1_nbXOfd721xHxH9MjeEJH2gKhu9Qb5jn",
    "drive_id": "1_nbXOfd721xHxH9MjeEJH2gKhu9Qb5jn",
    "drive_urls": [
      "1_nbXOfd721xHxH9MjeEJH2gKhu9Qb5jn"
    ]
  },
  {
    "id": "25G2097",
    "kanji": "西谷実莉",
    "last_name": "西谷",
    "first_name": "実莉",
    "kana": "にしたに みのり",
    "kana_full": "にしたにみのり",
    "romaji": "nisitani minori",
    "grade": 2,
    "dept": "厚生",
    "student_id": "25G2097",
    "faculty": "情報変革科学部",
    "department_name": "認知情報科学科",
    "birth": "2006/12/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1FhqqkxH6u6gMd8SVzP9tz-eRULLqnEkk",
    "drive_id": "1FhqqkxH6u6gMd8SVzP9tz-eRULLqnEkk",
    "drive_urls": [
      "1FhqqkxH6u6gMd8SVzP9tz-eRULLqnEkk"
    ]
  },
  {
    "id": "25G3107",
    "kanji": "橋本光明",
    "last_name": "橋本",
    "first_name": "光明",
    "kana": "はしもと みつあき",
    "kana_full": "はしもとみつあき",
    "romaji": "hasimoto mituaki",
    "grade": 2,
    "dept": "厚生",
    "student_id": "25G3107",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2007/2/20",
    "photo_url": "https://drive.google.com/uc?export=view&id=1ELv4VyHqAUHmWyuWmyHdWvN-_I65CxuL",
    "drive_id": "1ELv4VyHqAUHmWyuWmyHdWvN-_I65CxuL",
    "drive_urls": [
      "1ELv4VyHqAUHmWyuWmyHdWvN-_I65CxuL"
    ]
  },
  {
    "id": "26G1015",
    "kanji": "石川陽史",
    "last_name": "石川",
    "first_name": "陽史",
    "kana": "いしかわ はるふみ",
    "kana_full": "いしかわはるふみ",
    "romaji": "isikawa haruhumi",
    "grade": 1,
    "dept": "厚生",
    "student_id": "26G1015",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2006/05/21",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A4033",
    "kanji": "大槻悠斗",
    "last_name": "大槻",
    "first_name": "悠斗",
    "kana": "おおつき ゆうと",
    "kana_full": "おおつきゆうと",
    "romaji": "ootuki yuuto",
    "grade": 1,
    "dept": "厚生",
    "student_id": "26A4033",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2007/09/08",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26A4085",
    "kanji": "杉山雄也",
    "last_name": "杉山",
    "first_name": "雄也",
    "kana": "すぎやま ゆうや",
    "kana_full": "すぎやまゆうや",
    "romaji": "sugiyama yuuya",
    "grade": 1,
    "dept": "厚生",
    "student_id": "26A4085",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2007/01/29",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G3094",
    "kanji": "田邉蒼太",
    "last_name": "田邉",
    "first_name": "蒼太",
    "kana": "たなべ そうた",
    "kana_full": "たなべそうた",
    "romaji": "tanabe souta",
    "grade": 1,
    "dept": "厚生",
    "student_id": "26G3094",
    "faculty": "情報変革科学部",
    "department_name": "高度応用情報科学科",
    "birth": "2008/01/05",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "23B1015",
    "kanji": "上野瑛",
    "last_name": "上野",
    "first_name": "瑛",
    "kana": "うえの あきら",
    "kana_full": "うえのあきら",
    "romaji": "ueno akira",
    "grade": 4,
    "dept": "企画",
    "student_id": "23B1015",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2004/4/2",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "2332071",
    "kanji": "佐藤優真",
    "last_name": "佐藤",
    "first_name": "優真",
    "kana": "さとう ゆうま",
    "kana_full": "さとうゆうま",
    "romaji": "satou yuuma",
    "grade": 4,
    "dept": "企画",
    "student_id": "2332071",
    "faculty": "情報科学部",
    "department_name": "情報ネットワーク学科",
    "birth": "2004/10/22",
    "photo_url": "https://drive.google.com/uc?export=view&id=1fSb4pP0SPYIMuUbtVOj3q5L4tVB3Pgs5",
    "drive_id": "1fSb4pP0SPYIMuUbtVOj3q5L4tVB3Pgs5",
    "drive_urls": [
      "1fSb4pP0SPYIMuUbtVOj3q5L4tVB3Pgs5"
    ]
  },
  {
    "id": "23B2069",
    "kanji": "篠塚隼佑",
    "last_name": "篠塚",
    "first_name": "隼佑",
    "kana": "しのづか しゅんすけ",
    "kana_full": "しのづかしゅんすけ",
    "romaji": "sinoduka syunnsuke",
    "grade": 4,
    "dept": "企画",
    "student_id": "23B2069",
    "faculty": "創造工学部",
    "department_name": "都市環境工学科",
    "birth": "2003/8/6",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Nrqtqsykyz-Snl_h3f6bRQ_sBl2PN5xr",
    "drive_id": "1Nrqtqsykyz-Snl_h3f6bRQ_sBl2PN5xr",
    "drive_urls": [
      "1Nrqtqsykyz-Snl_h3f6bRQ_sBl2PN5xr"
    ]
  },
  {
    "id": "2331107",
    "kanji": "内藤優稀",
    "last_name": "内藤",
    "first_name": "優稀",
    "kana": "ないとう ゆうき",
    "kana_full": "ないとうゆうき",
    "romaji": "naitou yuuki",
    "grade": 4,
    "dept": "企画",
    "student_id": "2331107",
    "faculty": "情報科学部",
    "department_name": "情報工学科",
    "birth": "2004/12/28",
    "photo_url": "https://drive.google.com/uc?export=view&id=1gaLcei7MvhHxTGioosV00ZJiVD7aRS2v",
    "drive_id": "1gaLcei7MvhHxTGioosV00ZJiVD7aRS2v",
    "drive_urls": [
      "1gaLcei7MvhHxTGioosV00ZJiVD7aRS2v"
    ]
  },
  {
    "id": "2341098",
    "kanji": "中西凜",
    "last_name": "中西",
    "first_name": "凜",
    "kana": "なかにし りん",
    "kana_full": "なかにしりん",
    "romaji": "nakanisi rinn",
    "grade": 4,
    "dept": "企画",
    "student_id": "2341098",
    "faculty": "社会システム科学部",
    "department_name": "経営情報科学科",
    "birth": "2004/12/26",
    "photo_url": "https://drive.google.com/uc?export=view&id=1wC-8n8tE7qQ1HNHXU0Zh4wQLphI1rEmX",
    "drive_id": "1wC-8n8tE7qQ1HNHXU0Zh4wQLphI1rEmX",
    "drive_urls": [
      "1wC-8n8tE7qQ1HNHXU0Zh4wQLphI1rEmX"
    ]
  },
  {
    "id": "2342105",
    "kanji": "林朋花",
    "last_name": "林",
    "first_name": "朋花",
    "kana": "はやし ともか",
    "kana_full": "はやしともか",
    "romaji": "hayasi tomoka",
    "grade": 4,
    "dept": "企画",
    "student_id": "2342105",
    "faculty": "社会システム科学部",
    "department_name": "プロジェクトマネジメント学科",
    "birth": "2005/1/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=1smeqgo1Fj9Fri0pi-XajXyiM8qAmrPD3",
    "drive_id": "1smeqgo1Fj9Fri0pi-XajXyiM8qAmrPD3",
    "drive_urls": [
      "1smeqgo1Fj9Fri0pi-XajXyiM8qAmrPD3"
    ]
  },
  {
    "id": "24C2050",
    "kanji": "坂本こよみ",
    "last_name": "坂本",
    "first_name": "こよみ",
    "kana": "さかもと こよみ",
    "kana_full": "さかもとこよみ",
    "romaji": "sakamoto koyomi",
    "grade": 3,
    "dept": "企画",
    "student_id": "24C2050",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2004/12/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=16cUry58Bg_Ffs-fgmVaE_pRudy4ewUPr",
    "drive_id": "16cUry58Bg_Ffs-fgmVaE_pRudy4ewUPr",
    "drive_urls": [
      "16cUry58Bg_Ffs-fgmVaE_pRudy4ewUPr"
    ]
  },
  {
    "id": "24C3052",
    "kanji": "鷺坂のの",
    "last_name": "鷺坂",
    "first_name": "のの",
    "kana": "さぎさか のの",
    "kana_full": "さぎさかのの",
    "romaji": "sagisaka nono",
    "grade": 3,
    "dept": "企画",
    "student_id": "24C3052",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2006/2/13",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Ss-aNLpw2wBrbU3cs85bTvwtbDRcUwTM",
    "drive_id": "1Ss-aNLpw2wBrbU3cs85bTvwtbDRcUwTM",
    "drive_urls": [
      "1Ss-aNLpw2wBrbU3cs85bTvwtbDRcUwTM"
    ]
  },
  {
    "id": "24C3053",
    "kanji": "櫻井康佑",
    "last_name": "櫻井",
    "first_name": "康佑",
    "kana": "さくらい こうすけ",
    "kana_full": "さくらいこうすけ",
    "romaji": "sakurai kousuke",
    "grade": 3,
    "dept": "企画",
    "student_id": "24C3053",
    "faculty": "先進工学部",
    "department_name": "知能メディア工学科",
    "birth": "2005/9/15",
    "photo_url": "https://drive.google.com/uc?export=view&id=1P6T3xyj9VGH1Fid7esThPGBWpjn5D2X0",
    "drive_id": "1P6T3xyj9VGH1Fid7esThPGBWpjn5D2X0",
    "drive_urls": [
      "1P6T3xyj9VGH1Fid7esThPGBWpjn5D2X0"
    ]
  },
  {
    "id": "24C2056",
    "kanji": "佐々木るな",
    "last_name": "佐々木",
    "first_name": "るな",
    "kana": "ささき るな",
    "kana_full": "ささきるな",
    "romaji": "sasaki runa",
    "grade": 3,
    "dept": "企画",
    "student_id": "24C2056",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/6/11",
    "photo_url": "https://drive.google.com/uc?export=view&id=1ROoHd0rt7wVj_UBrlCzzZHJmlW_BZtn5",
    "drive_id": "1ROoHd0rt7wVj_UBrlCzzZHJmlW_BZtn5",
    "drive_urls": [
      "1ROoHd0rt7wVj_UBrlCzzZHJmlW_BZtn5"
    ]
  },
  {
    "id": "24C2117",
    "kanji": "村山夕輔",
    "last_name": "村山",
    "first_name": "夕輔",
    "kana": "むらやま ゆうすけ",
    "kana_full": "むらやまゆうすけ",
    "romaji": "murayama yuusuke",
    "grade": 3,
    "dept": "企画",
    "student_id": "24C2117",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2005/7/7",
    "photo_url": "https://drive.google.com/uc?export=view&id=1R9aJ2sXblHp-jFn3tk8t1L3hIJQv1NSo",
    "drive_id": "1R9aJ2sXblHp-jFn3tk8t1L3hIJQv1NSo",
    "drive_urls": [
      "1R9aJ2sXblHp-jFn3tk8t1L3hIJQv1NSo"
    ]
  },
  {
    "id": "25K1018",
    "kanji": "岩瀬晴香",
    "last_name": "岩瀬",
    "first_name": "晴香",
    "kana": "いわせ はるか",
    "kana_full": "いわせはるか",
    "romaji": "iwase haruka",
    "grade": 2,
    "dept": "企画",
    "student_id": "25K1018",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2006/9/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=1YMFtpmTmNMyUNIeGJt87ybmFlhHXAah0",
    "drive_id": "1YMFtpmTmNMyUNIeGJt87ybmFlhHXAah0",
    "drive_urls": [
      "1YMFtpmTmNMyUNIeGJt87ybmFlhHXAah0"
    ]
  },
  {
    "id": "25K2013",
    "kanji": "遠藤暖斗",
    "last_name": "遠藤",
    "first_name": "暖斗",
    "kana": "えんどう はると",
    "kana_full": "えんどうはると",
    "romaji": "enndou haruto",
    "grade": 2,
    "dept": "企画",
    "student_id": "25K2013",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2006/4/23",
    "photo_url": "https://drive.google.com/uc?export=view&id=1Z-L5qZ0QLZdrHRsMPmEAgesFM6P42pR2",
    "drive_id": "1Z-L5qZ0QLZdrHRsMPmEAgesFM6P42pR2",
    "drive_urls": [
      "1Z-L5qZ0QLZdrHRsMPmEAgesFM6P42pR2"
    ]
  },
  {
    "id": "25A4024",
    "kanji": "大石知弥",
    "last_name": "大石",
    "first_name": "知弥",
    "kana": "おおいし ともや",
    "kana_full": "おおいしともや",
    "romaji": "ooisi tomoya",
    "grade": 2,
    "dept": "企画",
    "student_id": "25A4024",
    "faculty": "工学部",
    "department_name": "電気電子工学科",
    "birth": "2006/4/8",
    "photo_url": "https://drive.google.com/uc?export=view&id=1FsNEG52I8HtfCShko0EUopxzYwuf-pJX",
    "drive_id": "1FsNEG52I8HtfCShko0EUopxzYwuf-pJX",
    "drive_urls": [
      "1FsNEG52I8HtfCShko0EUopxzYwuf-pJX"
    ]
  },
  {
    "id": "25B1049",
    "kanji": "川野紗和",
    "last_name": "川野",
    "first_name": "紗和",
    "kana": "かわの さわ",
    "kana_full": "かわのさわ",
    "romaji": "kawano sawa",
    "grade": 2,
    "dept": "企画",
    "student_id": "25B1049",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2006/11/19",
    "photo_url": "https://drive.google.com/uc?export=view&id=14lZ_m9xFMYWxNXsRFWXUXZvQJnOeDe4t",
    "drive_id": "14lZ_m9xFMYWxNXsRFWXUXZvQJnOeDe4t",
    "drive_urls": [
      "14lZ_m9xFMYWxNXsRFWXUXZvQJnOeDe4t"
    ]
  },
  {
    "id": "25A6105",
    "kanji": "前田旺佑",
    "last_name": "前田",
    "first_name": "旺佑",
    "kana": "まえだ おうすけ",
    "kana_full": "まえだおうすけ",
    "romaji": "maeda ousuke",
    "grade": 2,
    "dept": "企画",
    "student_id": "25A6105",
    "faculty": "工学部",
    "department_name": "応用化学科",
    "birth": "2006/10/14",
    "photo_url": "https://drive.google.com/uc?export=view&id=1tpGslg2cItqOfPBIfa9JttU6CqrV9jye",
    "drive_id": "1tpGslg2cItqOfPBIfa9JttU6CqrV9jye",
    "drive_urls": [
      "1tpGslg2cItqOfPBIfa9JttU6CqrV9jye"
    ]
  },
  {
    "id": "25C2116",
    "kanji": "松尾仁湖",
    "last_name": "松尾",
    "first_name": "仁湖",
    "kana": "まつお にこ",
    "kana_full": "まつおにこ",
    "romaji": "matuo niko",
    "grade": 2,
    "dept": "企画",
    "student_id": "25C2116",
    "faculty": "先進工学部",
    "department_name": "生命科学科",
    "birth": "2006/6/14",
    "photo_url": "https://drive.google.com/uc?export=view&id=1HKDYMYsyTdRDQeyAFhiccdZdHgy7U0DK",
    "drive_id": "1HKDYMYsyTdRDQeyAFhiccdZdHgy7U0DK",
    "drive_urls": [
      "1HKDYMYsyTdRDQeyAFhiccdZdHgy7U0DK"
    ]
  },
  {
    "id": "25B1150",
    "kanji": "矢田逞",
    "last_name": "矢田",
    "first_name": "逞",
    "kana": "やだ たくま",
    "kana_full": "やだたくま",
    "romaji": "yada takuma",
    "grade": 2,
    "dept": "企画",
    "student_id": "25B1150",
    "faculty": "創造工学部",
    "department_name": "建築学科",
    "birth": "2007/1/5",
    "photo_url": "https://drive.google.com/uc?export=view&id=1EwrxwPkA4Cfg4LyG7H8Z1N70UOEDpaJR",
    "drive_id": "1EwrxwPkA4Cfg4LyG7H8Z1N70UOEDpaJR",
    "drive_urls": [
      "1EwrxwPkA4Cfg4LyG7H8Z1N70UOEDpaJR"
    ]
  },
  {
    "id": "26K1045",
    "kanji": "鬼頭功樹",
    "last_name": "鬼頭",
    "first_name": "功樹",
    "kana": "きとう こうき",
    "kana_full": "きとうこうき",
    "romaji": "kitou kouki",
    "grade": 1,
    "dept": "企画",
    "student_id": "26K1045",
    "faculty": "未来変革科学部",
    "department_name": "デジタル変革科学科",
    "birth": "2008/03/09",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G2038",
    "kanji": "木村友哉",
    "last_name": "木村",
    "first_name": "友哉",
    "kana": "きむら ともや",
    "kana_full": "きむらともや",
    "romaji": "kimura tomoya",
    "grade": 1,
    "dept": "企画",
    "student_id": "26G2038",
    "faculty": "情報変革科学部",
    "department_name": "認知情報科学科",
    "birth": "2007/11/18",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26G1103",
    "kanji": "馬場幸希",
    "last_name": "馬場",
    "first_name": "幸希",
    "kana": "ばば こうき",
    "kana_full": "ばばこうき",
    "romaji": "baba kouki",
    "grade": 1,
    "dept": "企画",
    "student_id": "26G1103",
    "faculty": "情報変革科学部",
    "department_name": "情報工学科",
    "birth": "2008/02/15",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  },
  {
    "id": "26K2076",
    "kanji": "早川未桜",
    "last_name": "早川",
    "first_name": "未桜",
    "kana": "はやかわ みお",
    "kana_full": "はやかわみお",
    "romaji": "hayakawa mio",
    "grade": 1,
    "dept": "企画",
    "student_id": "26K2076",
    "faculty": "未来変革科学部",
    "department_name": "経営デザイン科学科",
    "birth": "2008/03/04",
    "photo_url": "https://drive.google.com/drive/folders/1M72MunlCSUVRP0kyylAgXQuG-uPLunH2VIRscfbNUFwyfLnPWo-lUvbBnuoc3TKkoxRqjuFz?usp=drive_link",
    "drive_id": "",
    "drive_urls": []
  }
];

window.INITIAL_RANKINGS = [
  { player_name: "坂井綾太", player_dept: "福祉", score: 1850, accuracy: 98.4, timestamp: "2026-09-01 12:00" },
  { player_name: "福原出雲", player_dept: "福祉", score: 1720, accuracy: 96.8, timestamp: "2026-09-01 14:30" },
  { player_name: "川上丈琉", player_dept: "総務", score: 1650, accuracy: 95.2, timestamp: "2026-09-01 16:15" },
  { player_name: "佐藤志帆", player_dept: "渉外", score: 1580, accuracy: 97.1, timestamp: "2026-09-01 18:00" },
  { player_name: "石川夏輝", player_dept: "財務", score: 1520, accuracy: 94.5, timestamp: "2026-09-01 19:20" },
  { player_name: "北村界翔", player_dept: "広報", score: 1490, accuracy: 93.0, timestamp: "2026-09-02 10:10" },
  { player_name: "青木遼斗", player_dept: "厚生", score: 1430, accuracy: 91.8, timestamp: "2026-09-02 11:45" },
  { player_name: "林朋花", player_dept: "企画", score: 1380, accuracy: 96.0, timestamp: "2026-09-02 13:00" }
];
